server:
  port: 8080
  servlet:
    context-path: /api

spring:
  application:
    name: smart-supply-chain-risk-intelligence
  
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: password
    
  h2:
    console:
      enabled: true
      path: /h2-console
      
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
    
firebase:
  project-id: ${FIREBASE_PROJECT_ID:rentvat}
  credentials-path: ${FIREBASE_CREDENTIALS_PATH:./service-account-key.json}

cors:
  allowed-origins: ${CORS_ALLOWED_ORIGINS:http://localhost:3000,http://127.0.0.1:3000}
  allowed-methods: GET,POST,PUT,DELETE,OPTIONS
  allowed-headers: "*"
  allow-credentials: true

logging:
  level:
    com.supply.chain: DEBUG
    org.springframework.security: DEBUG