spring:
  profiles: prod
  
  # PostgreSQL Database for Production
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/supply_chain_risk}
    driver-class-name: org.postgresql.Driver
    username: ${DATABASE_USERNAME:postgres}
    password: ${DATABASE_PASSWORD:password}
    
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    
  h2:
    console:
      enabled: false

# CORS Configuration for Production
cors:
  allowed-origins: 
    - ${FRONTEND_URL:https://supply-chain-risk.com}
  allowed-methods:
    - GET
    - POST
    - PUT
    - DELETE
    - OPTIONS
  allowed-headers: "*"
  allow-credentials: true

logging:
  level:
    com.supplychain.risk: INFO
    org.springframework.security: WARN