spring:
  config:
    activate:
      on-profile: dev
  
  # H2 Database for Development
  datasource:
    url: jdbc:h2:mem:devdb
    driver-class-name: org.h2.Driver
    username: sa
    password: password
    
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    defer-datasource-initialization: true
    
  # SQL Initialization
  sql:
    init:
      mode: never
    
  h2:
    console:
      enabled: true
      path: /h2-console

# CORS Configuration for Development
cors:
  allowed-origins: 
    - http://localhost:3000
    - http://127.0.0.1:3000
  allowed-methods:
    - GET
    - POST
    - PUT
    - DELETE
    - OPTIONS
  allowed-headers: "*"
  allow-credentials: true

logging:
  level:
    com.supplychain.risk: DEBUG
    org.springframework.security: DEBUG